version: "3.9"
services:

  tika:
    image: apache/tika:latest
    networks:
      - service-network
    ports:
      - "9998:9998"

  api:
    build: api
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    environment:
      - TIKA_URL=http://tika:9998/tika/forms
      - DEBUG=True
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    networks:
      - service-network



networks:
  service-network:
    driver: bridge